### ISSUE TITLE
lodash@4

### ISSUE THREAD

**Issue by FrancescoCioria** [buildo/webseed#1]
I think we should add `lodash@4+` as a default dependency for our projects.
Also, now that we have a beautiful webseed, we should also use [`babel-plugin-lodash`](https://github.com/lodash/babel-plugin-lodash) to safely replace this

``` js
import pick from 'lodash/pick'; // v4 has removed intermediate folders
import omit from 'lodash/omit';
```

with

``` js
import { pick, omit } from 'lodash';
```

**Comment by FrancescoCioria** [comment]
PS: after this we could also easily add an `eslint` plugin to prevent `import _ from 'lodash';`

**Comment by gabro** [comment]
Agreed. Actually in a separate branch I'm working on (not pushed yet) loadsh 4 is already there.
I'll give a spin to the babel plugin soon!

gabriele
~ buildo

**Comment by gabro** [comment]
Done in https://github.com/buildo/revenge-webseed/commit/6cf6948decb81e580b0fedca946b7864512587f7

**Comment by FrancescoCioria** [comment]
pro tip: you could use `hophop gh commit` :stuck_out_tongue_closed_eyes:

**Comment by gabro** [comment]
good point, but I was working on it without thinking about this issue. I realized later ;)
