### ISSUE TITLE
button size='large' triggers tcomb exception

### ISSUE THREAD

**Issue by dhinus** [buildo/webseed#15]
## description

If you open the chrome devtools, you get:

> message = "Invalid prop size supplied to Button, should be a "tiny" | "small" | "medium".
> Detected errors (1):
> 1. Invalid value "large" supplied to "tiny" | "small" | "medium"
## how to reproduce
- open the Chrome DevTools
- go to the Login form (`/login`)
## specs

Replacing 'large' with 'medium' seems an acceptable fix.
## misc

Another issue is the button becomes white-on-white when hovered. Is there any CSS class that's already available without writing additional CSS rules? Other ideas?

**Comment by gabro** [comment]
yes, buttons changed in a recent version of react-components.

replacing `large` with `mediums` is the right fix.

**Comment by giogonzo** [comment]
closed by 72da0eecdeb9ff9992125596f8a5dbb971a9868c
- Button props is happy
- style is not the best ever.. but at least no white hover :P
