### ISSUE TITLE
New app bootstrap

### ISSUE THREAD

**Issue by dhinus** [buildo/webseed#22]
## requirements

As a developer
I want a quick, standard way to bootstrap a new webseed-like app
So that I can go straight to the interesting stuff
## specs

Cloning the webseed repo is suboptimal because you have to remove the existing components/routes, remove the `.git` folder, remember to update the name and description in `package.json`, the Readme file, etc.

Some options, in increasing order of complexity:
- maintain a branch (or a separate repo) containing the minimal boilerplate (package.json, webpack config, etc.)
- minimise the boilerplate to a few lines that can be copy/pasted from the Readme (see #18)
- create a `buildo init` tool using a templated version of the boilerplate
- create a Yeoman generator (argh)
## misc

How did others solve this problem?
- React has a [starter kit](https://facebook.github.io/react/docs/getting-started.html) zipfile
- Angular 2 has a [webpage](https://angular.io/docs/ts/latest/quickstart.html) with accompanying [repo](https://github.com/angular/quickstart)
- Ember has a [ember new](https://guides.emberjs.com/v2.5.0/getting-started/quick-start/) command

Wise words from @lucacioria: "keep in mind the trade off between ease of use and complexity/maintainability of tooling"

**Comment by ecamellini** [comment]
@dhinus closing this, due to the latest webseed changes and objectives.
