### ISSUE TITLE
add script to check node/npm versions

### ISSUE THREAD

**Issue by FrancescoCioria** [buildo/webseed#25]
## requirements

we may want to check the versions of node/npm before installing/starting/building (we need this in some of out projects).

We could add a script to check node/npm versions and eventually throw an error if they're wrong.
## specs

something like this: https://github.com/buildo/hailadoc/pull/1841
maybe use the versions described in `engines` inside `package.json` to make it more visible/easy to edit?
## misc

{optional: other useful info}

**Comment by ecamellini** [comment]
@FrancescoCioria closing this, if there are no objections.
