### ISSUE TITLE
port new utilities from LOL

### ISSUE THREAD

**Issue by giogonzo** [buildo/webseed#4]
## proposal

mainly https://github.omnilab.our.buildo.io/buildo/aliniq/blob/master/labonline/web/src/app/components/Basic/containerFactory.js
and
https://github.omnilab.our.buildo.io/buildo/aliniq/blob/master/labonline/web/src/app/components/Basic/contains.js

they should probably be part of a separate module reused everywhere

tracking this here in the meantime

@gabro thoughts?

**Comment by gabro** [comment]
done in 876a910386ee845b5f630274ee781b01dcedf92a
