### ISSUE TITLE
[deps] App fails to start because of deps conflicts

### ISSUE THREAD

**Issue by dhinus** [buildo/webseed#7]
## description

The app fails to start because react-dom is not found
## how to reproduce
- clone the repo
- npm install (notice the peer dependencies errors)
- npm start
- error: `Module not found: Error: Cannot resolve module 'react-dom'`
## specs

Until we upgrade webseed to use React 0.14 (#6) we cannot use the latest version of react-components
## misc

@gabro pointed out there is a `react-0.13` branch of react-components we can use

**Comment by gabro** [comment]
👍 As discussed offline, pointing to the `react-0.13` branch fixes it.
